package emergon.ui;
// Generated 15 ??? 2021 3:03:53 ?? by Hibernate Tools 4.3.1


import emergon.entity.Activity;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Laborer generated by hbm2java
 */
@Entity
@Table(name="laborer"
    ,catalog="employees"
)
public class Laborer  implements java.io.Serializable {


     private long laborerid;
     private Activity activity;
     private String title;
     private String itemcode;
     private BigDecimal totalcost;

    public Laborer() {
    }

	
    public Laborer(long laborerid) {
        this.laborerid = laborerid;
    }
    public Laborer(long laborerid, Activity activity, String title, String itemcode, BigDecimal totalcost) {
       this.laborerid = laborerid;
       this.activity = activity;
       this.title = title;
       this.itemcode = itemcode;
       this.totalcost = totalcost;
    }
   
     @Id 

    
    @Column(name="laborerid", unique=true, nullable=false)
    public long getLaborerid() {
        return this.laborerid;
    }
    
    public void setLaborerid(long laborerid) {
        this.laborerid = laborerid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="activityid")
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }

    
    @Column(name="title", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="itemcode", length=100)
    public String getItemcode() {
        return this.itemcode;
    }
    
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }

    
    @Column(name="totalcost", precision=10, scale=5)
    public BigDecimal getTotalcost() {
        return this.totalcost;
    }
    
    public void setTotalcost(BigDecimal totalcost) {
        this.totalcost = totalcost;
    }

   




}


